/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Reports runtime and database health.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin login
         * @description Authenticates with email and password and returns a bearer token.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Returns the authenticated user resolved from the bearer token.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard summary
         * @description Returns aggregated counts and the 5 most recent unpaid invoices for the caller's organization. Requires ViewBilling capability.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit logs
         * @description Lists the organization's audit trail, newest first. Admin oversight — requires the manage_users capability (admin / superadmin).
         */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations */
        get: operations["listOrganizations"];
        put?: never;
        /** Create organization */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /** Get organization by id */
        get: operations["getOrganizationById"];
        put?: never;
        post?: never;
        /** Delete organization */
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /** Get user by id */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/admin/company-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get company settings
         * @description Returns the issuer profile for the caller's organization.
         */
        get: operations["getCompanySettings"];
        /**
         * Update company settings
         * @description Upserts the issuer profile (one record per organization).
         */
        put: operations["updateCompanySettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clients */
        get: operations["listClients"];
        put?: never;
        /** Create client */
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /** Get client by id */
        get: operations["getClientById"];
        put?: never;
        post?: never;
        /** Delete client */
        delete: operations["deleteClient"];
        options?: never;
        head?: never;
        /** Update client */
        patch: operations["updateClient"];
        trace?: never;
    };
    "/admin/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quotes */
        get: operations["listQuotes"];
        put?: never;
        /**
         * Create quote
         * @description Creates a draft quote; computes totals (round once per tax rate).
         */
        post: operations["createQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quotes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /** Get quote by id */
        get: operations["getQuoteById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change quote status
         * @description Transitions the quote status (draft→sent→accepted/rejected/expired).
         */
        patch: operations["changeQuoteStatus"];
        trace?: never;
    };
    "/admin/quotes/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /**
         * Download quote PDF
         * @description Generates and streams the quote as a PDF (見積書 layout). Requires ViewBilling capability. Returns application/pdf with Content-Disposition: attachment.
         */
        get: operations["getQuotePdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quotes/{id}/convert": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert quote to invoice
         * @description Converts an accepted quote into a draft invoice (copies lines/totals).
         */
        post: operations["convertQuoteToInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export invoices as CSV
         * @description Downloads all issued (non-draft) invoices for the organization as a UTF-8 BOM CSV file compatible with Excel and accounting software. Requires ViewBilling capability.
         */
        get: operations["exportInvoicesCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payments/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export payments as CSV
         * @description Downloads all valid (non-voided) payments for the organization as a UTF-8 BOM CSV file compatible with Excel and accounting software. Includes invoice number and client name for reference. Requires ViewBilling capability.
         */
        get: operations["exportPaymentsCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices */
        get: operations["listInvoices"];
        put?: never;
        /**
         * Create invoice
         * @description Creates a draft invoice directly (no originating quote).
         */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /** Get invoice by id */
        get: operations["getInvoiceById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /**
         * Download invoice PDF
         * @description Generates and streams the invoice as a PDF (適格請求書 layout when is_qualified_invoice is true). Requires ViewBilling capability. Returns application/pdf with Content-Disposition: attachment.
         */
        get: operations["getInvoicePdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices/{id}/download-token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate public download token
         * @description Generates a time-limited (7 days) public URL for the invoice PDF. The URL requires no authentication — share it with the client. Requires ManageBilling capability.
         */
        post: operations["generateDownloadToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/download/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        /**
         * Public PDF download
         * @description Downloads the invoice PDF using a previously generated token. No authentication required. Returns 404 for missing or expired tokens.
         */
        get: operations["downloadInvoicePdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices/{id}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue invoice
         * @description Issues a draft invoice: allocates an INV number and locks it. A qualified invoice requires the issuer registration number in company settings.
         */
        post: operations["issueInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices/{id}/send-email": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send invoice by email
         * @description Generates the invoice PDF and sends it to the client's email address. Requires the invoice to be in issued, partially_paid, or paid status and the client to have an email address. Requires ManageBilling capability.
         */
        post: operations["sendInvoiceEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invoices/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /**
         * List payments
         * @description Lists the payments recorded against an invoice.
         */
        get: operations["listPayments"];
        put?: never;
        /**
         * Record payment
         * @description Records a payment against an issued invoice and advances its status to partially_paid or paid. Amounts are integer cents; over-payment is rejected.
         */
        post: operations["recordPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details. */
        ProblemDetails: {
            /** @description Problem type URI (base https://nene-invoice.dev/problems/). */
            type: string;
            title: string;
            status: number;
            detail?: string;
        };
        HealthStatus: {
            /** @example ok */
            status: string;
            /** @example nene-invoice */
            service: string;
            checks?: {
                /** @example ok */
                database?: string;
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description HMAC bearer token (HS256). */
            token: string;
        };
        CurrentUser: {
            id: number;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            organization_id?: number | null;
        };
        /** @enum {string} */
        Role: "superadmin" | "admin" | "member" | "viewer";
        User: {
            id: number;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            organization_id?: number | null;
            /** @enum {string} */
            status?: "active" | "invited";
            created_at?: string | null;
            updated_at?: string | null;
        };
        UserList: components["schemas"]["PageEnvelope"];
        CreateUserRequest: {
            /** Format: email */
            email: string;
            password: string;
            role: components["schemas"]["Role"];
        };
        UpdateUserRequest: {
            /** Format: email */
            email?: string;
            password?: string;
            role?: components["schemas"]["Role"];
        };
        Organization: {
            id: number;
            name: string;
            slug: string;
            plan?: string | null;
            is_active: boolean;
            external_id?: string | null;
            custom_domain?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        OrganizationList: components["schemas"]["PageEnvelope"];
        CreateOrganizationRequest: {
            name: string;
            slug: string;
        };
        DownloadTokenResponse: {
            /** @description Public PDF download URL (relative path, no auth required). */
            url: string;
            /** @description Token expiry timestamp (Y-m-d H:i:s). */
            expires_at: string;
        };
        DashboardSummary: {
            /** @description Number of issued + partially_paid invoices. */
            unpaid_count: number;
            /** @description Number of invoices where is_overdue is true. */
            overdue_count: number;
            /** @description Sum of outstanding balance across all unpaid invoices, in cents. */
            outstanding_total_cents: number;
            /** @description Up to 5 most recent unpaid invoices, newest first. */
            recent_unpaid: components["schemas"]["Invoice"][];
            /** @description Sum of non-void payments received in the current month (paid_at based), in cents. */
            received_this_month_cents: number;
            /** @description Sum of non-void payments received in the previous month, in cents (for month-over-month comparison). */
            received_last_month_cents: number;
            aging: components["schemas"]["ReceivableAging"];
        };
        /** @description Outstanding receivable balance bucketed by overdue age, in cents. */
        ReceivableAging: {
            /** @description Not yet due (due_at null or in the future), in cents. */
            current: number;
            /** @description Overdue by 1–30 days, in cents. */
            overdue_1_30: number;
            /** @description Overdue by 31 days or more, in cents. */
            overdue_31_plus: number;
        };
        /** @description Issuer (自社) profile. registration_number is `T` + 13 digits. */
        CompanySettings: {
            organization_id: number;
            legal_name: string;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            registration_number?: string | null;
            bank_name?: string | null;
            bank_branch?: string | null;
            account_type?: string | null;
            account_number?: string | null;
            logo_url?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        UpdateCompanySettingsRequest: {
            legal_name: string;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            registration_number?: string | null;
            bank_name?: string | null;
            bank_branch?: string | null;
            account_type?: string | null;
            account_number?: string | null;
            logo_url?: string | null;
        };
        Client: {
            id: number;
            organization_id: number;
            name: string;
            contact_name?: string | null;
            email?: string | null;
            billing_address?: string | null;
            registration_number?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        ClientList: components["schemas"]["PageEnvelope"];
        CreateClientRequest: {
            name: string;
            contact_name?: string | null;
            email?: string | null;
            billing_address?: string | null;
            registration_number?: string | null;
        };
        UpdateClientRequest: {
            name?: string;
            contact_name?: string | null;
            email?: string | null;
            billing_address?: string | null;
            registration_number?: string | null;
        };
        /** @description A line on a quote or invoice. Money is integer cents. */
        LineItem: {
            id?: number;
            description: string;
            quantity: number;
            /** @description Unit price in integer cents (smallest currency unit). */
            unit_price_cents: number;
            /** @description Tax rate in basis points (1000 = 10%, 800 = 8%). */
            tax_rate_bps: number;
            sort_order?: number;
            /** @description quantity × unit_price_cents (pre-tax, not rounded). */
            line_subtotal_cents?: number;
        };
        LineItemInput: {
            description: string;
            quantity: number;
            unit_price_cents: number;
            /** @enum {integer} */
            tax_rate_bps: 800 | 1000;
        };
        Quote: {
            id: number;
            organization_id: number;
            client_id: number;
            /** @description Format EST-YYYY-NNN. */
            quote_number: string;
            /** @enum {string} */
            status: "draft" | "sent" | "accepted" | "rejected" | "expired";
            issued_at?: string | null;
            valid_until?: string | null;
            subtotal_cents: number;
            tax_cents: number;
            total_cents: number;
            notes?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        QuoteWithLines: components["schemas"]["Quote"] & {
            line_items?: components["schemas"]["LineItem"][];
        };
        QuoteList: components["schemas"]["PageEnvelope"];
        CreateQuoteRequest: {
            client_id: number;
            line_items: components["schemas"]["LineItemInput"][];
            valid_until?: string | null;
            notes?: string | null;
        };
        ChangeQuoteStatusRequest: {
            /** @enum {string} */
            status: "draft" | "sent" | "accepted" | "rejected" | "expired";
        };
        Invoice: {
            id: number;
            organization_id: number;
            client_id: number;
            quote_id?: number | null;
            /** @description Null until issued; format INV-YYYY-NNN. */
            invoice_number?: string | null;
            /** @enum {string} */
            status: "draft" | "issued" | "partially_paid" | "paid";
            /** @description Computed read-only field. True when status is issued or partially_paid and due_at is in the past. Always false for draft and paid invoices. */
            is_overdue: boolean;
            is_qualified_invoice: boolean;
            issued_at?: string | null;
            due_at?: string | null;
            subtotal_cents: number;
            tax_cents: number;
            total_cents: number;
            /** @description total_cents − Σ valid payments. Present on read endpoints (list / get); authoritative balance owned by Invoice. Integer cents. */
            outstanding_cents?: number;
            notes?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        InvoiceWithLines: components["schemas"]["Invoice"] & {
            line_items?: components["schemas"]["LineItem"][];
        };
        InvoiceList: components["schemas"]["PageEnvelope"];
        CreateInvoiceRequest: {
            client_id: number;
            line_items: components["schemas"]["LineItemInput"][];
            notes?: string | null;
        };
        IssueInvoiceRequest: {
            /**
             * @description Whether to issue as a qualified invoice (適格請求書).
             * @default true
             */
            qualified: boolean;
            due_at?: string | null;
        };
        Payment: {
            id: number;
            organization_id: number;
            invoice_id: number;
            /** @description Payment amount in integer cents. */
            amount_cents: number;
            paid_at: string;
            /** @enum {string|null} */
            method?: "bank_transfer" | "cash" | "other" | null;
            note?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        PaymentList: {
            items: components["schemas"]["Payment"][];
            total_paid_cents: number;
        };
        RecordPaymentRequest: {
            /** @description Payment amount in integer cents (positive). */
            amount_cents: number;
            paid_at?: string | null;
            /** @enum {string|null} */
            method?: "bank_transfer" | "cash" | "other" | null;
            note?: string | null;
        };
        RecordPaymentResponse: {
            payment: components["schemas"]["Payment"];
            invoice: components["schemas"]["Invoice"];
            total_paid_cents: number;
        };
        AuditLog: {
            id: number;
            actor_user_id?: number | null;
            organization_id?: number | null;
            /** @description e.g. invoice.created, invoice.issued, payment.recorded. */
            action: string;
            entity_type: string;
            entity_id?: number | null;
            before?: {
                [key: string]: unknown;
            } | null;
            after?: {
                [key: string]: unknown;
            } | null;
            created_at?: string | null;
        };
        AuditLogList: components["schemas"]["PageEnvelope"];
        /** @description Standard list envelope (items vary by endpoint). */
        PageEnvelope: {
            items: {
                [key: string]: unknown;
            }[];
            total: number;
            limit: number;
            offset: number;
        };
    };
    responses: {
        /** @description Missing or invalid bearer token, or bad credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but lacking the required capability. */
        InsufficientCapability: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource not found (or not in the caller's organization). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Conflicting request (e.g. cannot delete self). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Organization slug already in use. */
        SlugConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description User email already in use. */
        EmailConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Too many failed login attempts from the source IP. */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request body or field validation error. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Registration number is not `T` followed by 13 digits. */
        InvalidRegistrationNumber: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Disallowed status change. */
        InvalidStateTransition: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description A required qualified-invoice field is missing. */
        QualifiedInvoiceIncomplete: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Maximum number of items to return (1–100, default 20). */
        LimitParam: number;
        /** @description Number of items to skip (default 0). */
        OffsetParam: number;
        /** @description Resource identifier. */
        IdPathParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "service": "nene-invoice",
                     *       "checks": {
                     *         "database": "ok"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "admin@example.com",
                 *       "password": "secret"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                     *     }
                     */
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return (1–100, default 20). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of items to skip (default 0). */
                offset?: components["parameters"]["OffsetParam"];
                /** @description Filter by entity type (exact match), e.g. invoice, client. */
                entity_type?: string;
                /** @description Filter by action (exact match), e.g. invoice.issued. */
                action?: string;
                /** @description Filter by the acting user id (exact match). */
                actor_user_id?: number;
                /** @description Inclusive lower bound on created_at (YYYY-MM-DD or full datetime). */
                created_from?: string;
                /** @description Inclusive upper bound on created_at. A date-only value covers the whole day (expanded to 23:59:59). */
                created_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return (1–100, default 20). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of items to skip (default 0). */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Acme KK",
                 *       "slug": "acme"
                 *     }
                 */
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Organization created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            409: components["responses"]["SlugConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getOrganizationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return (1–100, default 20). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of items to skip (default 0). */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "member@example.com",
                 *       "password": "secret",
                 *       "role": "member"
                 *     }
                 */
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            409: components["responses"]["EmailConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["EmailConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getCompanySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCompanySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "legal_name": "Acme KK",
                 *       "registration_number": "T1234567890123"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateCompanySettingsRequest"];
            };
        };
        responses: {
            /** @description Company settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            422: components["responses"]["InvalidRegistrationNumber"];
        };
    };
    listClients: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return (1–100, default 20). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of items to skip (default 0). */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Buyer KK",
                 *       "registration_number": "T9876543210123"
                 *     }
                 */
                "application/json": components["schemas"]["CreateClientRequest"];
            };
        };
        responses: {
            /** @description Client created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            422: components["responses"]["InvalidRegistrationNumber"];
        };
    };
    getClientById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientRequest"];
            };
        };
        responses: {
            /** @description Client updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidRegistrationNumber"];
        };
    };
    listQuotes: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return (1–100, default 20). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of items to skip (default 0). */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    createQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "client_id": 1,
                 *       "line_items": [
                 *         {
                 *           "description": "Consulting",
                 *           "quantity": 1,
                 *           "unit_price_cents": 100000,
                 *           "tax_rate_bps": 1000
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["CreateQuoteRequest"];
            };
        };
        responses: {
            /** @description Quote created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteWithLines"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getQuoteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote with line items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteWithLines"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    changeQuoteStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "status": "sent"
                 *     }
                 */
                "application/json": components["schemas"]["ChangeQuoteStatusRequest"];
            };
        };
        responses: {
            /** @description Quote updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteWithLines"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidStateTransition"];
        };
    };
    getQuotePdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF binary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    convertQuoteToInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice created from quote */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceWithLines"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    exportInvoicesCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    exportPaymentsCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return (1–100, default 20). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of items to skip (default 0). */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
        };
    };
    createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "client_id": 1,
                 *       "line_items": [
                 *         {
                 *           "description": "License",
                 *           "quantity": 2,
                 *           "unit_price_cents": 50000,
                 *           "tax_rate_bps": 1000
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["CreateInvoiceRequest"];
            };
        };
        responses: {
            /** @description Invoice created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceWithLines"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getInvoiceById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice with line items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceWithLines"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    getInvoicePdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF binary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    generateDownloadToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadInvoicePdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF binary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    issueInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "qualified": true
                 *     }
                 */
                "application/json": components["schemas"]["IssueInvoiceRequest"];
            };
        };
        responses: {
            /** @description Invoice issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceWithLines"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["QualifiedInvoiceIncomplete"];
        };
    };
    sendInvoiceEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email sent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listPayments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payments for the invoice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
        };
    };
    recordPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "amount_cents": 110000,
                 *       "method": "bank_transfer"
                 *     }
                 */
                "application/json": components["schemas"]["RecordPaymentRequest"];
            };
        };
        responses: {
            /** @description Payment recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPaymentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["InsufficientCapability"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
}
